# Generated by Django 4.2.4 on 2023-09-01 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="device",
            name="last_inventory",
            field=models.DateField(blank=True, null=True),
        ),
    ]
