# Generated by Django 4.2.4 on 2023-08-16 07:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="device",
            name="device_ip",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="devices",
                to="device.deviceip",
            ),
        ),
        migrations.AlterField(
            model_name="deviceip",
            name="ip",
            field=models.GenericIPAddressField(unique=True),
        ),
    ]
