# Generated by Django 4.2.4 on 2023-08-21 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device', '0002_alter_device_device_ip_alter_deviceip_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicedepartment',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
