# Generated by Django 4.2.4 on 2023-08-20 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0002_alter_device_device_ip_alter_deviceip_ip"),
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="site",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user",
                to="device.devicesite",
            ),
        ),
    ]
