# Generated by Django 4.2.4 on 2023-08-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0002_alter_device_device_ip_alter_deviceip_ip"),
        ("user", "0002_alter_user_site"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="site",
        ),
        migrations.AddField(
            model_name="user",
            name="site",
            field=models.ManyToManyField(related_name="user", to="device.devicesite"),
        ),
    ]
